name: TVGFBF Monitor

on:
  schedule:
    - cron: "*/5 6-16 * * *"
  workflow_dispatch:

jobs:
  monitor:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Python kur
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Paketleri yükle
        run: |
          pip install requests beautifulsoup4

      - name: Script çalıştır
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: python monitor.py

      - name: seen.json kaydet
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

          git add seen.json
          git commit -m "update seen" || echo "No changes"
          git push
